#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data..."

# Loading buildings entities
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
    "actionType": "append",
    "entities": [
        {
            "id": "urn:ngsi-ld:Store:001",
            "type": "Store",
            "address":{
                "type": "PostalAddress",
                "value": {
                    "streetAddress": "C/ Octavio Cuartero, 4",
                    "addressLocality": "Albacete",
                    "postalCode": "02001",
                    "addressCountry": "Spain"
                }
            },
            "location": {
                "type": "geo:json",
                "value": {
                    "type": "Point",
                    "coordinates": [ -1.8570339054401495, 38.990913668029066]
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Store:002",
            "type": "Store",
            "address":{
                "type": "PostalAddress",
                "value": {
                    "streetAddress": "C/ Mayor, 10",
                    "addressLocality": "Albacete",
                    "postalCode": "02001",
                    "addressCountry": "Spain"
                }
            },
            "location": {
                "type": "geo:json",
                "value": {
                    "type": "Point",
                    "coordinates": [ -1.8568234873836609, 38.994465042377854]
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Store:003",
            "type": "Store",
            "address":{
                "type": "PostalAddress",
                "value": {
                    "streetAddress": "C/ San Juan, 6",
                    "addressLocality": "Albacete",
                    "postalCode": "02001",
                    "addressCountry": "Spain"
                }
            },
            "location": {
                "type": "geo:json",
                "value": {
                    "type": "Point",
                    "coordinates": [ -1.8519450432016082,38.98310104892331]
                }   
            }
        }
    ]
}'

# Loading Products entities
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
    "actionType": "append",
    "entities": [
        {
            "id": "urn:ngsi-ld:Product:001",
            "type": "Product",
            "name": {
                "type": "Text",
                "value": "Apple"
            },
            "category": {
                "type": "Text",
                "value": "Fruit"
            },
            "price": {
                "type": "Number",
                "value": 1.5,
                "metadata": { "currency": { "type": "Text", "value": "EUR" }}
            }
        },
        {
            "id": "urn:ngsi-ld:Product:002",
            "type": "Product",
            "name": {
                "type": "Text",
                "value": "Bread"
            },
            "category": {
                "type": "Text",
                "value": "Bakery"
            },
            "price": {
                "type": "Number",
                "value": 1.2,
                "metadata": { "currency": { "type": "Text", "value": "EUR" } }
            }
        },
        {
            "id": "urn:ngsi-ld:Product:003",
            "type": "Product",
            "name": {
                "type": "Text",
                "value": "Milk"
            },
            "category": {
                "type": "Text",
                "value": "Dairy"
            },
            "price": {
                "type": "Number",
                "value": 0.9,
                "metadata": { "currency": { "type": "Text", "value": "EUR" }}
            }
        }
    ]
}'

# Loading Inventory entities
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
    "actionType": "append",
    "entities": [
        {
            "id": "urn:ngsi-ld:Inventory:001",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:001"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:001"
            },
            "stockCount": {
                "type": "Number",
                "value": 50
                }
        },
        {
            "id": "urn:ngsi-ld:Inventory:002",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:001"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:002"
            },
            "stockCount": {
                "type": "Number",
                "value": 30
                }
        },
        {
            "id": "urn:ngsi-ld:Inventory:003",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:001"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:003"
            },
            "stockCount": {
                "type": "Number",
                "value": 20
                }
        },
        {
            "id": "urn:ngsi-ld:Inventory:004",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:002"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:001"
            },
            "stockCount": {
                "type": "Number",
                "value": 50
                }
        },
        {
            "id": "urn:ngsi-ld:Inventory:005",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:002"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:002"
            },
            "stockCount": {
                "type": "Number",
                "value": 30
                }
        },
        {
            "id": "urn:ngsi-ld:Inventory:006",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:002"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:003"
            },
            "stockCount": {
                "type": "Number",
                "value": 20
                }
        },
        {
            "id": "urn:ngsi-ld:Inventory:007",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:003"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:001"
            },
            "stockCount": {
                "type": "Number",
                "value": 50
                }
        },
        {
            "id": "urn:ngsi-ld:Inventory:008",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:003"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:002"
            },
            "stockCount": {
                "type": "Number",
                "value": 30
                }
        },
        {
            "id": "urn:ngsi-ld:Inventory:009",
            "type": "Inventory",
            "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Store:003"
            },
            "refProduct": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Product:003"
            },
            "stockCount": {
                "type": "Number",
                "value": 20
                }
        }
    ]
}'

printf " ✅ Done\n"