#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data..."

# Loading buildings entities
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
    "actionType": "append",
    "entities": [
        {
            "id": "urn:ngsi-ld:Building:001",
            "type": "Building",
            "address":{
                "type": "PostalAddress",
                "value": {
                    "streetAddress": "C/ Octavio Cuartero, 4",
                    "addressLocality": "Albacete",
                    "postalCode": "02001",
                    "addressCountry": "Spain"
                }
            },
            "location": {
                "type": "geo:json",
                "value": {
                    "type": "Point",
                    "coordinates": [ -1.8570339054401495, 38.990913668029066]
                }   
            }
        }
    ]
}'

# Loading flats entities
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
    "actionType": "append",
    "entities": [
        {
            "id": "urn:ngsi-ld:Flat:001",
            "type": "Flat",
            "refBuilding": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Building:001"
            },
            "floor": {
                "type": "Number",
                "value": 1
            },
            "door": {
                "type": "Text",
                "value": "A"
            }  
        },
        {
            "id": "urn:ngsi-ld:Flat:002",
            "type": "Flat",
            "refBuilding": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Building:001"
            },
            "floor": {
                "type": "Number",
                "value": 1
            },
            "door": {
                "type": "Text",
                "value": "B"
            }
        },
        {
            "id": "urn:ngsi-ld:Flat:003",
            "type": "Flat",
            "refBuilding": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Building:001"
            },
            "floor": {
                "type": "Number",
                "value": 2
            },
            "door": {
                "type": "Text",
                "value": "A"
            }
        },
        {
            "id": "urn:ngsi-ld:Flat:004",
            "type": "Flat",
            "refBuilding": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Building:001"
            },
            "floor": {
                "type": "Number",
                "value": 2
            },
            "door": {
                "type": "Text",
                "value": "B"
            }
        }
    ]
}
'


# Loading rooms entities
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
    "actionType": "append",
    "entities":[
        {
            "id": "urn:ngsi-ld:Room:Flat1Room1",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:001"
            },
            "name": {
                "type": "Text",
                "value": "Living Room"  
            },
            "area": {
                "type": "Number",
                "value": 20,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Room:Flat1Room2",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:001"
            },
            "name": {
                "type": "Text",
                "value": "Bedroom"  
            },
            "area": {
                "type": "Number",
                "value": 15,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat1Room3",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:001"
            },
            "name": {
                "type": "Text",
                "value": "Bedroom"  
            },
            "area": {
                "type": "Number",
                "value": 12,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat1Room4",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:001"
            },
            "name": {
                "type": "Text",
                "value": "Kitchen"  
            },
            "area": {
                "type": "Number",
                "value": 14,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat1Room5",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:001"
            },
            "name": {
                "type": "Text",
                "value": "Bathroom"  
            },
            "area": {
                "type": "Number",
                "value": 8,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat2Room1",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:002"
            },
            "name": {
                "type": "Text",
                "value": "Living Room"  
            },
            "area": {
                "type": "Number",
                "value": 22,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Room:Flat2Room2",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:002"
            },
            "name": {
                "type": "Text",
                "value": "Bedroom"  
            },
            "area": {
                "type": "Number",
                "value": 16,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat2Room3",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:002"
            },
            "name": {
                "type": "Text",
                "value": "Bedroom"  
            },
            "area": {
                "type": "Number",
                "value": 13,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Room:Flat2Room4",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:002"
            },
            "name": {
                "type": "Text",
                "value": "Kitchen"  
            },
            "area": {
                "type": "Number",
                "value": 15,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat2Room5",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:002"
            },
            "name": {
                "type": "Text",
                "value": "Bathroom"  
            },
            "area": {
                "type": "Number",
                "value": 9,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat3Room1",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:003"
            },
            "name": {
                "type": "Text",
                "value": "Living Room"  
            },
            "area": {
                "type": "Number",
                "value": 18,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Room:Flat3Room2",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:003"
            },
            "name": {
                "type": "Text",
                "value": "Bedroom"  
            },
            "area": {
                "type": "Number",
                "value": 14,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat3Room3",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:003"
            },
            "name": {
                "type": "Text",
                "value": "Bedroom"  
            },
            "area": {
                "type": "Number",
                "value": 11,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Room:Flat3Room4",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:003"
            },
            "name": {
                "type": "Text",
                "value": "Kitchen"  
            },
            "area": {
                "type": "Number",
                "value": 13,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat3Room5",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:003"
            },
            "name": {
                "type": "Text",
                "value": "Bathroom" 
            },
            "area": {
                "type": "Number",
                "value": 9,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }
            }
        },
        {
            "id": "urn:ngsi-ld:Room:Flat4Room1",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:004"
            },
            "name": {
                "type": "Text",
                "value": "Living Room"  
            },
            "area": {
                "type": "Number",
                "value": 19,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Room:Flat4Room2",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:004"
            },
            "name": {
                "type": "Text",
                "value": "Bedroom"  
            },
            "area": {
                "type": "Number",
                "value": 15,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat4Room3",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:004"
            },
            "name": {
                "type": "Text",
                "value": "Bedroom"  
            },
            "area": {
                "type": "Number",
                "value": 12,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }
        },
        {
            "id": "urn:ngsi-ld:Room:Flat4Room4",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:004"
            },
            "name": {
                "type": "Text",
                "value": "Kitchen"  
            },
            "area": {
                "type": "Number",
                "value": 14,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }   
            }   
        },
        {
            "id": "urn:ngsi-ld:Room:Flat4Room5",
            "type": "Room",
            "refFlat": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Flat:004"
            },
            "name": {
                "type": "Text",
                "value": "Bathroom"  
            },
            "area": {
                "type": "Number",
                "value": 8,
                "metadata": {
                    "unitCode": {
                        "type": "Text",
                        "value": "MTK"
                    }
                }
            }
        }
    ]
}'

# printf "⏳ Loading sensors entities "
# # Loading sensors entities
# curl -s -o /dev/null -X POST \
#   'http://orion:1026/v2/op/update' \
#   -H 'Content-Type: application/json' \
#   -g -d '@./sensors.json'

echo -e " \033[1;32mdone\033[0m"