# CRUD Operations for FIWARE NGSI-v2

#General settings
@orion=localhost:1026
@webserver4Windows=host.docker.internal:1234
@webserver4Linux=172.18.1.1:1234
@webserver4Mac=host.docker.internal:1234
#Set webserver depending on your OS
@webserver={{webserver4Linux}}
#@webserver={{webserver4Windows}}
#@webserver={{webserver4Mac}}


### Check Python web server is running
POST http://{{webserver}}/subscription/attr-change
Content-Type: application/json

{
    "message": "Hello world!!"
}   


### List all entities to verify update
GET http://{{orion}}/v2/entities?options=keyValues

## SUBSCRIPTIONS QUERIES
### Query sensors with a battery level above 80%
POST http://{{orion}}/v2/subscriptions
Content-Type: application/json

{
    "description": "Notify when battery level is above 10%",
    "subject":{
        "entities": [
            {
                "idPattern": ".*",
                "type": "Sensor"
            }
        ],
        "condition": {
            "attrs": ["batteryLevel"],
            "expression": {"q": "batteryLevel<10"}
        }
    },
    "notification": {
        "http": {
            "url": "http://{{webserver}}/subscription/attr-change"
        },
        "attrs": ["room", "batteryLevel"],
        "attrsFormat": "keyValues"
    },
    "throttling": 0
}

### Get all subscriptions
# @name getSubscriptions
GET http://{{orion}}/v2/subscriptions

### Update battery level of sensor s1, s5 bellow 10% to trigger the subscription
POST http://{{orion}}/v2/op/update
Content-Type: application/json

{
    "actionType": "update",
    "entities": [
        {
            "id": "urn:ngsi-ld:Sensor:s1",
            "batteryLevel": { "value": 3.1}
        },
        {
            "id": "urn:ngsi-ld:Sensor:s5",
            "batteryLevel": { "value": 5.0}
        }  
    ]
}

### Update subscription to disable throttling
@SubscriptionId = {{getSubscriptions.response.body.$[0].id}}
PATCH http://{{orion}}/v2/subscriptions/{{SubscriptionId}}
Content-Type: application/json

{
    "state": "inactive"
}

### Update battery level of sensor s2, s3 and s4 bellow 10% to trigger the subscription
POST http://{{orion}}/v2/op/update
Content-Type: application/json

{
    "actionType": "update",
    "entities": [
        {
            "id": "urn:ngsi-ld:Sensor:s2",
            "batteryLevel": { "value": 4.0}
        },
        {
            "id": "urn:ngsi-ld:Sensor:s3",
            "batteryLevel": { "value": 2.0}
        },
        {
            "id": "urn:ngsi-ld:Sensor:s4",
            "batteryLevel": { "value": 1.0}
        }  
    ]
}

### Notificate with humidity > 70% and temperature > 26ºC
POST http://{{orion}}/v2/subscriptions/
Content-Type: application/json

{
    "description": "Notify when humidity is above 70% and temperature above 26ºC",
    "subject":{
        "entities": [
            {
                "idPattern": ".*",
                "type": "Sensor"
            }
        ],
        "condition": {
            "attrs": ["humidity"],
            "expression": {"q": "humidity>70.0;temperature>26"} 
        }
    },
    "notification": {
        "http": {
            "url": "http://{{webserver}}/subscription/attr-change"
        },
        "attrs": ["room", "temperature", "humidity"],
        "attrsFormat": "keyValues"
    }
}


### Update temperature and humidity of some sensors to trigger the subscription
POST http://{{orion}}/v2/op/update
Content-Type: application/json

{
    "actionType": "update",
    "entities": [
        {
            "id": "urn:ngsi-ld:Sensor:s5",
            "temperature": { "value": 19.0}
        },
        {
            "id": "urn:ngsi-ld:Sensor:s4",
            "humidity": { "value": 92.0}
        },
        {
            "id": "urn:ngsi-ld:Sensor:s6",
            "temperature": { "value": 31.5},
            "humidity": {"value": 61.0}
        },
        {
            "id" : "urn:ngsi-ld:Sensor:s1",
            "temperature": { "value": 28.0 },
            "humidity": {"value": 71.0}
        }
    ]
}

### Get all subscriptions
# @name getSubscriptions2
GET http://{{orion}}/v2/subscriptions



### Delete Subscriptions
@SubscriptionId1 = {{getSubscriptions2.response.body.$[0].id}}
@SubscriptionId2 = {{getSubscriptions2.response.body.$[1].id}}
DELETE http://{{orion}}/v2/subscriptions/{{SubscriptionId1}}
Accept: application/json

###
DELETE http://{{orion}}/v2/subscriptions/{{SubscriptionId2}}
Accept: application/json



### Query all sensors
POST http://{{orion}}/v2/op/query?options=keyValues
Content-Type: application/json

{
    "entities": [
        {
            "idPattern": ".*",
            "type": "Sensor"
        }
    ],
    "attrs": [
        "room",
        "temperature",
        "humidity",
        "batteryLevel"
    ]
}


